# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-08 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': '板块', 'verbose_name_plural': '板块'},
        ),
        migrations.AlterModelOptions(
            name='forumpost',
            options={'verbose_name': '帖子', 'verbose_name_plural': '帖子'},
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='total_likes',
            field=models.IntegerField(default=0, verbose_name='推荐数'),
        ),
    ]
