# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-08 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160514_0813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '博客', 'verbose_name_plural': '博客'},
        ),
    ]
