# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_auto_20160514_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtopic',
            name='users_like',
        ),
        migrations.AlterField(
            model_name='foodtopic',
            name='foods',
            field=models.ManyToManyField(related_name='topics_belong', to='food.Food', verbose_name='美食'),
        ),
    ]
