# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_foodtopic_total_collects'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtopic',
            name='cover_image',
            field=models.ImageField(default='qwe', upload_to='topic/cover/%Y/%m/%d', verbose_name='封面图片'),
            preserve_default=False,
        ),
    ]
