# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0005_foodtopic_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtopic',
            name='description',
            field=models.TextField(default='123', verbose_name='专题描述'),
            preserve_default=False,
        ),
    ]
