# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20160515_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='introduction',
            field=models.TextField(blank=True, max_length=1024, verbose_name='个人简介'),
        ),
    ]
