# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 05:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('cover_image', models.ImageField(upload_to='items/cover/%Y/%m/%d', verbose_name='封面图片')),
                ('link', models.URLField(blank=True, verbose_name='相关链接')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '美食',
                'verbose_name_plural': '美食',
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '美食分类',
                'verbose_name_plural': '美食分类',
            },
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='food.FoodCategory', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='food',
            name='comments',
            field=models.ManyToManyField(blank=True, to='comments.Comment', verbose_name='评论'),
        ),
        migrations.AddField(
            model_name='food',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='food',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods_shared', to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AddField(
            model_name='food',
            name='users_collect',
            field=models.ManyToManyField(blank=True, related_name='foods_collected', to=settings.AUTH_USER_MODEL, verbose_name='收藏的用户'),
        ),
        migrations.AddField(
            model_name='food',
            name='users_dislike',
            field=models.ManyToManyField(blank=True, related_name='foods_disliked', to=settings.AUTH_USER_MODEL, verbose_name='不喜欢的用户'),
        ),
        migrations.AddField(
            model_name='food',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='foods_liked', to=settings.AUTH_USER_MODEL, verbose_name='喜欢的用户'),
        ),
    ]
