# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 07:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0002_auto_20160514_0738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': '食品', 'verbose_name_plural': '食品'},
        ),
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name': '食品分类', 'verbose_name_plural': '食品分类'},
        ),
        migrations.RemoveField(
            model_name='food',
            name='users_collect',
        ),
        migrations.AddField(
            model_name='food',
            name='users_ate',
            field=models.ManyToManyField(blank=True, related_name='foods_ate', to=settings.AUTH_USER_MODEL, verbose_name='吃过的用户'),
        ),
        migrations.AddField(
            model_name='food',
            name='users_wta',
            field=models.ManyToManyField(blank=True, related_name='foods_wta', to=settings.AUTH_USER_MODEL, verbose_name='想吃的用户'),
        ),
        migrations.AlterField(
            model_name='food',
            name='cover_image',
            field=models.ImageField(upload_to='foods/cover/%Y/%m/%d', verbose_name='封面图片'),
        ),
    ]
