# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20160515_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='total_dislikes',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='不喜欢数'),
        ),
        migrations.AddField(
            model_name='food',
            name='total_likes',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='喜欢数'),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='food.FoodCategory', verbose_name='分类'),
        ),
    ]
