# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20160522_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='total_dislikes',
        ),
        migrations.RemoveField(
            model_name='food',
            name='total_likes',
        ),
        migrations.RemoveField(
            model_name='food',
            name='users_dislike',
        ),
        migrations.RemoveField(
            model_name='food',
            name='users_like',
        ),
        migrations.AddField(
            model_name='food',
            name='rating_dislikes',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='food',
            name='rating_likes',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
    ]
